### ISSUE TITLE
[Feature request] IR support with IRremoteESP8266

### ISSUE THREAD

**Issue by scop** [OttoWinter/esphomelib#107]
Would be cool to have IR device functionality using https://github.com/markszabo/IRremoteESP8266, including support for more elaborate devices such as the HVAC's it supports.

**Comment by OttoWinter** [comment]
esphomelib has its own IR sending/receiving engine using the Remote Transmitter/Receivers here: https://esphomelib.com/esphomeyaml/index.html#misc-components

It doesn't support all of IRremote's protocols yet, but using the raw values directly is quite easy anyway   with esphomeyaml

**Comment by OttoWinter** [comment]
esphomelib has many IR codes now, more code groups will be added in the future (see Add IR codes issue)
