### ISSUE TITLE
wifi connection problems

### ISSUE THREAD

**Issue by tomeeka** [OttoWinter/esphomelib#113]
Hello Otto,

I am using wemos d1 mini boards with esp easy, but i want to migrate to esphome. (I hate clicking on that slow webconfig menu...)
I have tried esphomelib&yaml, and they are are great!
But I have a few wifi issues...

1.
Cant connect to hidden ssid.

2.
I have a wemos d1 mini in a room where the wifi signal is weaker. With esphomelib, it does not connect to my router. If I move the board closer, than it is ok. With esp easy I have no such issue before. I compiled the sample webserver project with platform io and it is working fine too in that room. (restarted the board several times, and in a few seconds it reconnects, but not with esphome)

I plugged the board into my laptop and checked the logs through serial.
![wifi1](https://user-images.githubusercontent.com/41842441/43361131-93856c72-92c7-11e8-9c5d-95151b728252.JPG)

One time the project crashed and never recovered from that point.
![wifi2](https://user-images.githubusercontent.com/41842441/43361133-9de1288c-92c7-11e8-9384-65b538f165b8.JPG)

Could you help me with these? I really like esphomelib&yaml but I have 2 more boards that are far from the router, and I am affraid if I upload new firmware on them they will never come back.

Thanks!

**Comment by tomeeka** [comment]
Tested with a different board (maybe hw problem) but same issue. :(

**Comment by TheJulianJES** [comment]
I flashed esphomelib with esphomeyaml on some NodeMCU boads (worked perfectly) and also on three Sonoff Basics, only two of them worked. And the other one didn't connect to the wifi at all and rebooted. I'll try to flash Tasmota and see if that connects to WiFi. If that works, I'll try flashing esphomelib again.

**Comment by ormstont** [comment]
I'm having a very similar issue - tried it on several Wemos D1 Minis and had no problems at all, connected straight away. I tried it on two Sonoff Basics and one worked initially but then after a few more flashes wouldn't connect. The other never connected. Tasmota on them connects with no problems.

**Comment by stoinov** [comment]
Same here with latest 1.7.0 - Wemos D1 mini unable to connect even though tasmota works on it.

**Comment by aptonline** [comment]
Yep getting the same here on both Wemos D1 mini and a NodeMCU, both work fine with Tasmota. I may have wrongly posted this issue in the esphomeyaml issues:

https://github.com/OttoWinter/esphomeyaml/issues/108

**Comment by jollybully** [comment]
@inforsgit I'm getting the exact same issue, initial upload works with sonoff basic, subsequent uploads knock out WiFi. WiFi works fine with Tasmoata

**Comment by AlexMekkering** [comment]
I'm experiencing the same issues with a Wemos D1 Mini pro and a NodeMCU v2. I've tried two different Wifi networks and they simply won't connect.
An ESP32 I have connects without problems.

**Comment by OttoWinter** [comment]
esphomelib/yaml v1.8.0 now defaults to choosing a relatively recent arduino framework version which works a lot better than the previous default. This, I hope at least, should eliminate at least part of this problem.

**Comment by tomeeka** [comment]
Hi Otto, I have been testing the new version since last night. So far so good. :) I really appreciate your hard work! Greetings from Hungary!

**Comment by OttoWinter** [comment]
Closing this issue as it has apparently gotten a lot better in recent versions from what I've heard so far. It's still not perfect but for further discussion I will set up a central issue where all these "wifi and/or mqtt" issues will be linked to.
