### ISSUE TITLE
FastLED effects do not respect the the targeted brightness

### ISSUE THREAD

**Issue by TheJulianJES** [OttoWinter/esphomelib#117]
When choosing an effect for a FastLED controllable strip (in my case a WS2811), the effect always seems to be on brightness 100%.
I also encountered this when trying to rebuild some effects of previously created sketches.
https://i.imgur.com/O6PeyVa.png // https://hastebin.com/amoyuxuruy.cpp
A method that lets us have access in the ```apply_effect``` would be perfect. (maybe in LightState which accesses the LightTransformer getTargetValues()?)

**Comment by OttoWinter** [comment]
Uhm yes, true - thanks for pointing this out!

**Comment by OttoWinter** [comment]
Fixed in the next release (together with a big effects overhaul).
