### ISSUE TITLE
Platform for Wemos ESP-WROOM-02

### ISSUE THREAD

**Issue by ezar** [OttoWinter/esphomelib#121]
I have a [wemos ESP-WROOM-02](https://www.ebay.com/itm/WeMos-D1-Esp-Wroom-02-Motherboard-ESP8266-Mini-WiFi-Nodemcu-Module-18650-Battery-/172684188367) and I want to manage using esphomelib. What platform we need to use?
Regards.

**Comment by lobradov** [comment]
http://docs.platformio.org/en/latest/platforms/espressif8266.html#boards

`esp_wroom_02`

**Comment by davericher** [comment]
it is actually lolin32

esphomeyaml:
  name:                  aThing
  platform:              ESP32
  board:                 lolin32

**Comment by OttoWinter** [comment]
In esphomeyaml 1.10.0 the user will be shown a dialog in the dashboard with all available platform options. And instructions what to do when the platform is not found. Part of https://github.com/OttoWinter/esphomeyaml/pull/234 (will be split up into multiple PRs)
