### ISSUE TITLE
[Feature Request] Please add weight sensor amplifier module HX711

### ISSUE THREAD

**Issue by nevalain** [OttoWinter/esphomelib#129]
This module can be used in many ways:
 - Occupancy sensors (e.g. bed)
 - Weight sensor (container empty etc.)

**Comment by cgtobi** [comment]
This has already been implemented by @OttoWinter 2 weeks ago.

https://github.com/OttoWinter/esphomelib/search?q=hx711&type=Code

**Comment by nevalain** [comment]
Thanks. Closing.
