### ISSUE TITLE
Heartbeat filter for binary_sensor

### ISSUE THREAD

**Issue by mnoorenberghe** [OttoWinter/esphomelib#140]
An esphomeyaml device I deployed some months ago updates binary sensors on an interval even without a change but I noticed that the latest code changed that and only publishes on changes. That's not great for how I want to use it (I don't want the overhead of a separate availability topic) so I thought a `heartbeat` filter would work but I guess that isn't valid for binary_sensor according to the yaml validation messages. Can the `heartbeat` filter please be supported for `binary_sensor` components? The workaround mentioned in https://github.com/OttoWinter/esphomelib/issues/126#issuecomment-412329027 may work but isn't great.

**Comment by OttoWinter** [comment]
Uhm sure, I added it locally now and it should be in the next release.
