### ISSUE TITLE
Failover for wifi: multiple access point connection 

### ISSUE THREAD

**Issue by nerdosity** [OttoWinter/esphomelib#145]
Hello,

On Tasmota and ESPEasy you can setup a failover wifi connection, to which the ESP will try to connect.
On ESPurna, you can set up as many secondary access point as you wish.

I have a 802.11n SSID for every domotic device, but sometimes (it's an USB one on my OpenWRT router) it will disappear for some minutes, maybe some problem with power supply.
Can you please add this feature? 

It could easily be added like this:

- if the wifi: exists, it will use just that
- if there are multiple wifi_0:, wifi_1:, wifi_2:, it will try to connect to them from 0 to 2

**Comment by OttoWinter** [comment]
Closing for #49
