### ISSUE TITLE
A wiki link is missed

### ISSUE THREAD

**Issue by voicevon** [OttoWinter/esphomelib#163]
https://github.com/OttoWinter/esphomelib/wiki/Custom-Sensor-Component
Move the page down to bottom. There is a link. but the link doesn't work.

**Comment by OttoWinter** [comment]
I'm not maintaining the esphomelib wiki anymore. The guide over at https://esphomelib.com/esphomeyaml/components/sensor/custom.html should also work fine even without using esphomeyaml, but I really don't want to have to maintain two versions of the same *long* guide.

I removed the wiki entry now :P
