### ISSUE TITLE
Looking for ideas 

### ISSUE THREAD

**Issue by rlust** [OttoWinter/esphomelib#192]
I am looking for ideas on how to get Home Assistant data to display on ESPHOMEYAML display?

How to get sensor data from HA as an item to show on display.

**Comment by OttoWinter** [comment]
I'm not sure, but I think you figured it out anyway, right?

Just for reference, this can be done using text sensors: https://beta.esphomelib.com/esphomeyaml/components/text_sensor/mqtt_subscribe.html#example-usage-for-displays
