### ISSUE TITLE
ESP32 mqtt disconect from broker

### ISSUE THREAD

**Issue by ghost** [OttoWinter/esphomelib#246]
Hi I have weird problem with my ESP32. Every 10-15 days it disconnected from MQTT broker and can not connect without reset by button or unplug electricity. It is same for all my ESP32 but ESP8266 work without any problems. 
Any idea what to do with this? 
Thanks for ideas

setup
```C
 App.set_name("loznice_postel");
    LogComponent *logComponent = App.init_log(115200, 1024);
    logComponent->set_global_log_level(ESPHOMELIB_LOG_LEVEL_WARN);
    App.init_wifi("**", "**");
    App.init_mqtt("***", "**", "**");
        App.make_dht_sensor("Loznice teplomer", "Loznice vlhkost", GPIOOutputPin(13)).dht->set_dht_model(DHT_MODEL_DHT22);
    Application::MakeLight light = App.make_monochromatic_light("Loznice svetlo", App.make_ledc_output(27));
    pComponent = App.make_esp32_touch_component();
    ESP32TouchBinarySensor *pSensor = pComponent->make_touch_pad("Touch 4", TOUCH_PAD_NUM6, 330);
    pComponent->set_iir_filter(20);
      App.setup();
```
Graph when ESP32 is unavailable. Small parts are only few seconds that is ok but that 2 long parts are few hours and end after hard reset
![nedostupny](https://user-images.githubusercontent.com/2417999/47702178-6cf52400-dc1c-11e8-85a8-43936b3bdd5f.png)

**Comment by HFsi** [comment]
Which broker do you use, guys?

**Comment by xsimek20** [comment]
I use this addon https://github.com/hassio-addons/addon-mqtt/blob/master/README.md  which used https://mosquitto.org broker. I don't think it is broker issue. Which version of board did you used for build (I mean platformio or arduino board version) for working ESP32?

**Comment by HFsi** [comment]
I haven´t been working with ESP32 yet, only ESP8266.
My question was about the broker, because the embedded on HA wasn´t working so good.
I´m now running on mosquitto and everything seems fine.
