### ISSUE TITLE
integrate automesh 

### ISSUE THREAD

**Issue by voicevon** [OttoWinter/esphomelib#249]
What new integration would you wish to have?
auto mesh

https://github.com/martin-ger/esp_wifi_repeater/blob/master/AutoMesh.JPG

Do you have any plan already?

**Comment by OttoWinter** [comment]
See https://github.com/OttoWinter/esphomelib/issues/247#issuecomment-435416804 - No, esphomelib won't do that.

The primary reasons are that:
 * a) implementing such a feature would be extremely complex. Just look at the code base you linked to. Supporting meshing makes handling WiFi a thousand times more difficult.
 * b) As the project you linked to reads on the first page, using ESPs as repeaters is quite unstable and sometimes crashes the ESPs. I don't want to have to maintain such a thing which will get many issues over time.

If you want to have auto-meshing nodes, you can use the other project, esphomelib unfortunately won't do that.
