### ISSUE TITLE
AM2320 temperature/humidity support

### ISSUE THREAD

**Issue by bencer** [OttoWinter/esphomelib#324]
**What new integration would you wish to have?**
DHT sensor module support AM2302, but there is a new version of that sensor AM2320 that doesn't currently work.

**If possible, provide a link to an existing library for the integration:**
https://github.com/adafruit/Adafruit_AM2320
https://github.com/hibikiledo/AM2320

**Please describe your use case for this integration and alternatives you've tried:**
Use case is temperature / humidity monitoring, like DHT sensors but with an updated sensor version.

Most probably this should be just supporting model: AM2320 within the DHT sensor.

**Comment by OttoWinter** [comment]
It's just another name for this sensor: https://esphomelib.com/esphomeyaml/components/sensor/dht12.html
