### ISSUE TITLE
Can not use previous version

### ISSUE THREAD

**Issue by tomlut** [OttoWinter/esphomelib#403]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio 0.85.1, Pi 3B
**ESP (ESP32/ESP8266/Board/Sonoff):**

Not relevant
**Affected component:**

The esphomeyaml addon

**Description of problem:**

I tried to use the previous version by addding the following (as per the instructions in the addon) to my addon config, saving and restarting the addon:

```
{
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "port": 6052,
  "esphomeyaml_version": "v1.9.0"
}
```

However this just results in:

502 Bad Gateway
nginx/1.14.0 (Ubuntu)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
```

**Traceback (if applicable):**

```

```

**Additional information:**

The following is in the addon log repeatedly:
```

esphomeyaml: error: unrecognized arguments: --socket /var/run/esphomeyaml.sock --hassio
[19:12:23+1100] INFO ----> Starting esphomeyaml dashboard...
usage: esphomeyaml [-h] [-v]
                   configuration
                   {config,compile,upload,logs,run,clean-mqtt,wizard,mqtt-fingerprint,version,clean,dashboard,hass-config}
```
                   ...

**Comment by OttoWinter** [comment]
Please read the documentation for that option. Usually the versions must match to guarantee operation - that is also the case here.

In 1.10, a new option was added so that the dashboard could be started on a UNIX socket, which makes specifying versions before 1.10.0 impossible with this version. Future versions (unless something else is changed) will be usable though.

**Comment by tomlut** [comment]
Ok, is there any way to revert to an earlier version of the Hassio addon?

**Comment by OttoWinter** [comment]
Not until Hass.io adds such an option, no.

**Comment by tomlut** [comment]
Right-o. Thanks.

**Comment by tomlut** [comment]
Thought I'd ound a method to downgrade. Partial snapshot restore. But the web front end is not reachable.  Log:

```
nginx: [emerg] host not found in "default_server" of the "listen" directive in /etc/nginx/nginx.conf:27
[10:15:33+1100] INFO ----> Starting NGINX...
```

**Comment by OttoWinter** [comment]
Snapshots don't restore addon images (only their data). So sorry, not possible :/

**Comment by tomlut** [comment]
Ah, right. Thanks for the explanation.
