### ISSUE TITLE
API Reference unavailable 

### ISSUE THREAD

**Issue by rsdatatechnologies** [OttoWinter/esphomelib#41]
Hi Everyone,

I've just discovered this awesome project today but the API Reference on https://esphomelib.com/api/ doesn't seem to be working. 

Here's an example of what I see on the Light Color Values section:

`Warning
doxygenclass: Cannot find class “esphomelib::light::LightColorValues” in doxygen xml output for project “esphomelib” from directory: ./_doxyxml/`

**Comment by OttoWinter** [comment]
Weird... something broke the doxygen build. I've now re-triggered the docs build and it seems to be fixed now. However, it's now using the latest master branch version not 1.2.1. I'll probably release 1.3 in the next few days or even today anyway.
