### ISSUE TITLE
Generic i2c (binary) sensor

### ISSUE THREAD

**Issue by apeeters** [OttoWinter/esphomelib#45]
Hi,

I would be nice to support a generic binary sensor such as PCF8574A or PCF8574P.

Keep up the excellent work!

**Comment by OttoWinter** [comment]
Thanks for the suggestion! Seems like a relatively simple protocol those I/O expanders use, so probably won't be too difficult to integrate them into esphomelib. I'll take a closer look at it next week 👍

Note to self: [this library](https://github.com/RobTillaart/Arduino/blob/master/libraries/PCF8574/PCF8574.cpp) seems like a good starting point to implement the i²c communication part.

**Comment by OttoWinter** [comment]
So this is working now if I understand correctly... Closing this feature request
