### ISSUE TITLE
Support for ESP32's hall sensor

### ISSUE THREAD

**Issue by fabaff** [OttoWinter/esphomelib#54]
The ESP32 has a built-in [hall sensor](https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf). It's possible to use [`hallRead()`](https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-adc.c#L236) in the Arduino IDE.

```c
void loop() {
  int hall = 0;
  hall = hallRead();
  Serial.println(hall); 
	delay(3000);
}
```

I guess that it would only be useful for people who don't have any real sensors around to play with an actual sensor value beside using ADC pin and touch them :wink: .

**Comment by OttoWinter** [comment]
Done 😺

https://github.com/OttoWinter/esphomelib/commit/f1703fa5703488881cabad476a0b859fa8a6ba1f
https://github.com/OttoWinter/esphomeyaml/commit/4f3f460105a569d9c27419a9ed9e1237094bcccb
https://github.com/OttoWinter/esphomedocs/commit/59e58c23083ebaa825357841b517b41630479256
