### ISSUE TITLE
Read secrets from secrets.yaml

### ISSUE THREAD

**Issue by anthonyangel** [OttoWinter/esphomelib#60]
esphomelib requires some sensitive values to be written into config (e.g. wifi password, MQTT password), this means that the config files can't be committed to Git, and there's duplication between the homeassistant config

Is it possible for esphomelib to read secrets form the homeassistant secrets.yaml file, or to pull in secrets from env vars?

**Comment by OttoWinter** [comment]
See https://esphomelib.com/esphomeyaml/guides/faq.html#tips-for-using-esphomeyaml :)

**Comment by anthonyangel** [comment]
I though that I read the docs first before opening this - now I feel stupid for not finding it!

Thanks very much
