### ISSUE TITLE
WLAN RSSI sensor

### ISSUE THREAD

**Issue by brandond** [OttoWinter/esphomelib#61]
I might take this one on myself as a learning opportunity - but it would be nice to be able to report the wifi signal strength. I know this is available in STA mode on ESP32; not sure about ESP8266.

**Comment by OttoWinter** [comment]
If you were not referring to this, maybe have a look at this: https://gist.github.com/OttoWinter/ab9ec0b17c8f54a64db220af5b65b911 - from what I see it should also work with the ESP8266

**Comment by brandond** [comment]
Super simple, but good for getting my feet wet in the codebase.
