### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [OttoWinter/esphomelib#80]
Are you using the normal ESP Wire library, which is compatible with the Arduino Wire library ? Then there is no need to wait after Wire.requestFrom().

In the file "esphomelib/src/esphomelib/i2c_component.cpp", in the function "read_()" the while-loop with the available() and the timeout and the yield() can be removed.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by OttoWinter** [comment]
Ah yes thank you for that. At first I thought it would be different for the ESP32, but there the buffer also seems to be filled by the `requestFrom` call as you said.

Thanks 😺
