### ISSUE TITLE
Bad dependency link in README.md

### ISSUE THREAD

**Issue by ayavilevich** [OttoWinter/esphomelib#84]
The link https://github.com/marvinroger/async-mqtt-client/releases in the Arduino dependency section links to version 0.8.1 of the library which doesn't support ESP32. As a result the build will fail.
Link can be updated to master.zip directly which will be ok.

**Comment by OttoWinter** [comment]
Interesting... I wonder why it works with platformio with ESPs, it must be using the master branch...

Anyway, thanks for reporting this, I'll fix it.

**Comment by ayavilevich** [comment]
@OttoWinter perhaps this is because platformio doesn't use the "architectures" field in library.properties .

If it uses library.json then it can explain it, as in 0.8.1 it was defined more broadly for platformio than for Arduino.
https://github.com/marvinroger/async-mqtt-client/commit/d60ad9e17540938510f28876cf59f90a4374de0f#diff-5a96806328fdf598e651d77cf92879fe
