### ISSUE TITLE
[Feature Request] NTC10K Sensor Support

### ISSUE THREAD

**Issue by Mervoes** [OttoWinter/esphomelib#89]
Can you add a support for that sensor?

**Comment by brandond** [comment]
Seems like it's be pretty easy to support any PTC/NTC thermistor if you just write a lambda to convert the GPIO analog voltage reading to a temperature. You'd need to look up or calculate (with a multimeter) the resistance for whatever model you're using.

**Comment by OttoWinter** [comment]
Closing as it's a simple ADC sensor and already possible. I have ordered one for myself and will add detailed instructions in the docs when it arrives.

**Comment by OttoWinter** [comment]
Update: added as a proper component now here https://github.com/esphome/esphome/pull/560

Reason was that the calculation required (and calibration) is more complicated than it should be.
