### ISSUE TITLE
[Feature Request] Please add CO2 sensor MH-Z19 

### ISSUE THREAD

**Issue by nevalain** [OttoWinter/esphomelib#94]
Co2 sensor MH-Z19 would be great!

**Comment by balk77** [comment]
The [ESP Easy plugin](https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P049_MHZ19.ino) for MH-Z19 could be used as a basis. Unfortunately I have no clue how to write such module.... I can help debugging though.

**Comment by OttoWinter** [comment]
Yep, mine arrived a few days ago. The protocol looks quite simple so I hope I can get it into 1.8.0

**Comment by ThellraAK** [comment]
Is UART used anywhere else, I can't find anything searching around, but it seems like it would be easier to add soft UART https://github.com/plieningerweb/esp8266-software-uart and use then be able to just send and receive things to it.

**Comment by OttoWinter** [comment]
Done :) it's in 1.8.0
